#!/usr/bin/env python3
"""Build the canonical mark module from the logo assets, and repoint the render at it.

`bonk-mark-v2.js` holds the same drawing but as a TRACE of it: one cubic control point
reads 1078.41 where the asset says 1078.63, a 0.22-unit deviation on a 262-unit mark
(0.08%). Good enough to have shipped, but the asset you sent carries the real vectors,
so the canonical module is generated from those and the traced metrics are carried over
rather than re-derived -- they were measured from the same drawing and agree to 1 dp.

Emits `projects/logo/current/bonk-mark.js` exposing BOTH `window.BONK_MARK` (what the
motion system reads) and `window.BONK_MARK_V2` (what the blueprint v2 reads), so either
can load this one file instead of reaching into superseded paths.

Also repoints bonk-motion-system-v3.html at it. v3 was loading wordmark-paths.js, which
is a DIFFERENT mark entirely: 302.1 x 257.0, aspect 1.1755, letterCount 4, against this
one's 626.92 x 261.90, aspect 2.3935, 6 glyphs. Mask-diff IoU between them: 0.342.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path("/Users/suhaas/Pictures/motion - design - assets")
ASSET = ROOT / "projects/logo/current/bonk-new-logo-black-svg.svg"
V2 = ROOT / "projects/blueprint/public/bonk-mark-v2.js"
OUT = ROOT / "projects/logo/current/bonk-mark.js"
V3 = ROOT / "projects/motion-system/bonk-motion-system-v3.html"

# ── 1. the asset's real vectors ─────────────────────────────────────────────
svg = ASSET.read_text()
glyph_paths = re.findall(r'<path d="([^"]+)" fill="black"', svg)
if len(glyph_paths) != 6:
    sys.exit(f"ABORT — expected 6 glyph paths (fill=black), found {len(glyph_paths)}")
d = "".join(p.strip() for p in glyph_paths)

# ── 2. the traced module supplies the measured metrics + profile ────────────
mod = json.loads(V2.read_text()[V2.read_text().index("{"): V2.read_text().rindex("}") + 1])
meta = {k: mod[k] for k in ("width", "height", "origin", "letters", "metrics", "profile")
        if k in mod}

# ── 3. emit ────────────────────────────────────────────────────────────────
payload = dict(meta)
payload["d"] = d
payload["source"] = "logo/new-logo-assets (bonk new logo - svg/black - svg.svg, exact vectors)"

body = json.dumps(payload, separators=(",", ":"))
OUT.write_text(
    "// generated by projects/logo/extract_current_mark.py — do not hand-edit\n"
    "// Source: 'bonk new logo assets' -> black - svg.svg. EXACT vector data, not a trace.\n"
    "// Metrics/profile are carried from extract_mark2.py's measurement of the same\n"
    "// drawing (its traced d differed by one control point: 1078.41 vs 1078.63, 0.08%).\n"
    "// Exposes both names so any render can load this one file.\n"
    f"window.BONK_MARK = {body};\n"
    f"window.BONK_MARK_V2 = window.BONK_MARK;\n"
)
print(f"═══ {OUT.relative_to(ROOT)}")
print(f"   {OUT.stat().st_size:,} b   d = {len(d):,} ch of exact vectors across {len(glyph_paths)} paths")
print(f"   width {payload['width']}  height {payload['height']}"
      f"  origin {payload['origin']}  letters {len(payload['letters'])}")
print(f"   metrics {payload['metrics']}")

# ── 4. repoint v3 ──────────────────────────────────────────────────────────
src = V3.read_text()
edits = [
    ('<script src="../blueprint/public/wordmark-paths.js"></script>',
     '<script src="../logo/current/bonk-mark.js"></script>', 1),
    ("const MARK = window.BONK_MARK;\n"
     "if (!MARK) throw new Error('wordmark-paths.js did not load — check ../blueprint/public/');",
     "const MARK = window.BONK_MARK;\n"
     "if (!MARK) throw new Error('bonk-mark.js did not load — check ../logo/current/');", 1),
    # d is in the asset's own 2000x2000 space, so the mark's origin must be removed
    # or every panel draws it shifted by origin*s (687*s, 869*s). TWO sites need this:
    # makePanel, and primSpecimen's per-cell marks, which build their own matrix.
    ("  const m = new DOMMatrix().translate(ox, oy).scale(s, s);",
     "  const m = new DOMMatrix().translate(ox, oy).scale(s, s)\n"
     "                            .translate(-MARK.origin.x, -MARK.origin.y);",
     2),
]
for old, new, want in edits:
    n = src.count(old)
    if n != want:
        sys.exit(f"ABORT — anchor found {n}x (need {want}), {V3.name} untouched:\n  {old[:80]}...")
    src = src.replace(old, new)

# the header comment names the old source
src = src.replace(
    " * Rendering is a pure function of time",
    " * The mark is loaded from ../logo/current/bonk-mark.js — the asset you sent, exact\n"
    " * vectors. v3 previously rendered wordmark-paths.js, a DIFFERENT mark (302.1x257.0,\n"
    " * aspect 1.1755, 4 letters; IoU 0.342 against this one).\n"
    " *\n * Rendering is a pure function of time", 1)
V3.write_text(src)
print(f"\n═══ repointed {V3.name}  ({len(src):,} bytes)")
print(f"   wordmark-paths refs remaining: {src.count('wordmark-paths')}")
print(f"   bonk-mark.js refs: {src.count('bonk-mark.js')}")
